export const Icons = {
	menu: "heroicons:bars-3",
	logout: "hugeicons:logout-02",
	user: "hugeicons:user-03",
	save: "hugeicons:floppy-disk",
	undo: "hugeicons:undo-02",
	redo: "hugeicons:redo-02",
	cut: "hugeicons:scissor",
	copy: "hugeicons:copy-01",
	paste: "hugeicons:task-01",
	delete: "hugeicons:delete-02",
	noSelection: "hugeicons:add-circle-half-dot",
	command: "hugeicons:command",
	text: "hugeicons:text",
	brush: "hugeicons:brush",
	components: "hugeicons:layers-01",
	shapes: "hugeicons:square",
	add: "hugeicons:add-01",
	remove: "hugeicons:remove-01",
	instantBooking: "hugeicons:zap",
	approvalRequired: "hugeicons:hourglass",
	rectangle: "material-symbols-light:rectangle-outline",
	circle: "material-symbols-light:circle-outline",
	select: "hugeicons:cursor-02",
	penTool: "hugeicons:pen-tool-03",
};
